import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navigations/Navbar/Navbar";
import Footer from "@/components/navigations/Footer";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/redux/providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "CELCIUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen seccond-font">
        <Providers>
          <Navbar />
          <main className="relative min-h-screen">{children}</main>
          <Footer />
          <Toaster position="top-right" />
        </Providers>
        <Script
          src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL}
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
