import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navigations/Navbar/Navbar";
import Footer from "@/components/navigations/Footer";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/redux/providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "CELCIUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen seccond-font">
        <Providers>
          <Navbar />
          <main className="relative min-h-screen">{children}</main>
          <Footer />
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3500,
              className: "seccond-font",
              style: {
                background: "#171717",
                color: "#fafafa",
                borderRadius: 0,
                fontSize: "13px",
                padding: "12px 16px",
                boxShadow: "0 8px 24px rgba(0,0,0,0.16)",
              },
              success: {
                iconTheme: { primary: "#fafafa", secondary: "#171717" },
              },
              error: {
                iconTheme: { primary: "#fafafa", secondary: "#171717" },
              },
            }}
          />
        </Providers>
        <Script
          src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL}
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
